### ISSUE TITLE
Wavedash item pickup

### ISSUE THREAD

**Issue by AnalogSSBM** [HDR-Development/HDR-Nightlies#1]
Hi, I understand that the recent ecb changes allow for smoother wavedashes, which I think is great. 

However, after playing and testing in the current nightly build and switching back to beta I noticed that I can no longer pick up items with wavedash in the current nightly build. 

I could still pick them up however if I intentionally delayed my wavedash so that I entered an airborne air dodge state. After testing in frame advance mode it seems I would have to delay my wavedash until the third airborne frame. So now I guess it would be better to just pick it up with attack. But wavedashing was a much quicker and more efficient way to handle grounded items imo.

But it works great in the beta. Very similar to pm.

Its something I really love and would miss if it goes away. But, at the same time I understand if the ecb changes take priority over a niche mechanic like this.

Just thought it would be worth a shot to keep one of my favorite mechanics in the game.

I respect the decision nonetheless and love this game and appreciate all the hard work that has gone into it <3

- Analog :)

**Comment by Riah321** [comment]
You might want to resubmit this over with the rest of the issues (and then close this issue)
https://github.com/HDR-Development/HewDraw-Remix/issues
